
# /app/src/inventree-app.git/android/key.properties

storePassword=Segment-Linguini-Talcum-Scam-Afar-Hurdle6
keyPassword=Deduce-Sizzle4-Pretzel-Correct-Purify-Senator
keyAlias=key
storeFile=/tmp/keys.jks"
